/**
 * Endgame Enhancement Economy v1.1 — 30 günlük, büyük kohortlu deney raporu (Simulation Only).
 *   npx tsx tests/sim/population/enh11-long.ts ctrlDir1,ctrlDir2,... expDir1,expDir2,... [çıktı.md]
 * MATURE_COHORT_ASSUMPTION: başlangıç seviyesi ≥ meta.COH olan oyuncular +9 takımla başlar (iki kolda da). Diğerleri "doğal ilerleyen".
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { computeStats, hitDamage, type Item } from '../../../shared/game';
const sum = (a: number[]) => a.reduce((s, x) => s + x, 0); const avg = (a: number[]) => (a.length ? sum(a) / a.length : 0);
const f0 = (n: number) => Math.round(n).toLocaleString('tr-TR'); const f1 = (n: number) => n.toFixed(1); const f2 = (n: number) => n.toFixed(2); const P = (n: number) => `%${(n * 100).toFixed(1)}`; const K = (n: number) => `${(n / 1000).toFixed(0)}k`; const Mn = (n: number) => `${(n / 1e6).toFixed(2)}M`;
const load = (dirs: string) => dirs.split(',').map((d) => JSON.parse(readFileSync(`${d}/ham.json`, 'utf8')));
const stats = (a: any) => computeStats({ level: a.final.level, boy: a.boy, spec: a.final.spec, equip: a.def as Record<string, Item>, kut: a.final.kut });
const ttk = (A: any, B: any) => { const sa = stats(A), sb = stats(B); const crit = 1 + Math.min(1, sa.crit / 100) * (sa.critMult - 1); return (sb.maxHp / Math.max(1, hitDamage(sa.atk, 1, sb.def, true, false) * crit)) * sa.atkInterval; };
const C = load(process.argv[2]), X = load(process.argv[3]); const COH = C[0].meta.COH as number; const DAYS = C[0].meta.DAYS as number;
const mature = (a: any) => a.seedLevel >= COH;
const L: string[] = []; const w = (s = '') => L.push(s); const mean = (arr: any[], f: (x: any) => number) => avg(arr.map(f));
const grpOf = (k: string) => k === 'artı +10…+15' ? 'enh' : k === 'kımız' ? 'kimiz' : k === 'kostüm: şans eşyası' ? 'luck' : k.startsWith('kostüm') ? 'kostum' : k === 'artı basma' ? 'up9' : 'other';
const econ = (D: any) => { const E: any[] = D.econ; const src = sum(E.map((e) => sum(Object.values(e.sources) as number[]))); const g: Record<string, number> = { enh: 0, kimiz: 0, luck: 0, kostum: 0, up9: 0, other: 0 }; for (const e of E) for (const [k, v] of Object.entries(e.sinks)) g[grpOf(k)] += v as number; const snk = sum(Object.values(g)); const gold = D.agents.map((a: any) => a.days[a.days.length - 1].gold).sort((x: number, y: number) => x - y); return { src, snk, g, net: src - snk, tot: sum(gold), med: gold[Math.floor(gold.length / 2)], top: avg(gold.slice(Math.floor(gold.length * 0.9))) }; };
const EC = C.map(econ), EX = X.map(econ);
const row = (name: string, c: number, x: number, fmt: (n: number) => string) => w(`| ${name} | ${fmt(c)} | ${fmt(x)} | ${c ? (((x - c) / Math.abs(c)) * 100 >= 0 ? '+' : '') + (((x - c) / Math.abs(c)) * 100).toFixed(1) + '%' : '—'} |`);
const LABEL = process.env.LABEL ?? 'v1.1';
w(`# Endgame Enhancement Economy ${LABEL} — 30 günlük deney (Simulation Only)\n\n${C.length} seed · ${DAYS} gün · 150 oyuncu · kilitli profil (baseline_heavy, KZ 0,09, NPC 0,70, Mob %100, Kımız 0,6) · oranlar 40/32/25/18/12/8 (değiştirilmedi).\n\n> **MATURE_COHORT_ASSUMPTION:** başlangıç seviyesi ≥ ${COH} olan oyuncular (ortalama ${f1(mean(C, (D) => D.agents.filter(mature).length))} kişi) **+9 takımla başlıyor** — iki kolda da. Bu yapay bir başlangıç koşuludur; gerçek oyundaki erişilebilirliği temsil etmez. Bu yüzden "olgun +9 kohortu" ile "doğal ilerleyen oyuncular" (ortalama ${f1(mean(C, (D) => D.agents.filter((a: any) => !mature(a)).length))} kişi) ayrı raporlanır.\nKontrol = +9 tavan, ${LABEL} = +10…+15 açık. Değerler seed ortalamasıdır.\n`);
w('## 1. +13–+15 gerçekten oluşuyor mu? (deney kolu, oyuncu oranı: ekipmanında ≥+n olan)\n');
const snaps = [1, 3, 7, 10, 14, 21, 30].filter((d) => d <= DAYS);
for (const [name, pick] of [['Olgun +9 kohortu', mature], ['Doğal ilerleyen oyuncular', (a: any) => !mature(a)]] as [string, (a: any) => boolean][]) {
  w(`**${name}**\n\n| Gün | ≥+10 | ≥+11 | ≥+12 | ≥+13 | ≥+14 | +15 |\n|---|---|---|---|---|---|---|`);
  for (const d of snaps) { const cells = [10, 11, 12, 13, 14, 15].map((t) => avg(X.map((D) => { const idx = D.agents.map((a: any, i: number) => (pick(a) ? i : -1)).filter((i: number) => i >= 0); const du = D.dayUps[d - 1]; return idx.length ? idx.filter((i: number) => Math.max(0, ...du.agents[i].ups) >= t).length / idx.length : 0; }))); w(`| ${d} | ${cells.map(P).join(' | ')} |`); }
  w();
}
w('Kontrol kolunda (+9 tavan) ≥+10 oranı tanım gereği %0.\n');
w('**Doğal ilerleyenlerin erişimi (30. gün, ekipmanında ≥+n olan oran; Kontrol / deney):**\n\n| ≥+5 | ≥+6 | ≥+7 | ≥+8 | ≥+9 |\n|---|---|---|---|---|');
{ const at = (R: any[], t: number) => avg(R.map((D) => { const idx = D.agents.map((a: any, i: number) => (!mature(a) ? i : -1)).filter((i: number) => i >= 0); const du = D.dayUps[DAYS - 1]; return idx.filter((i: number) => Math.max(0, ...du.agents[i].ups) >= t).length / idx.length; })); w(`| ${[5, 6, 7, 8, 9].map((t) => `${P(at(C, t))} / ${P(at(X, t))}`).join(' | ')} |\n`); }
w('**Deneme ve başarı (deney kolu, seed ortalaması):**\n\n| Hedef | Tasarım şansı | Deneme | Başarı | Gerçek oran | Düşme | Tılsım koruması (≈) |\n|---|---|---|---|---|---|---|'); const RT: any = { 10: '40%', 11: '32%', 12: '25%', 13: '18%', 14: '12%', 15: '8%' };
const ext = (D: any, k: string) => sum(D.agents.map((a: any) => a.ext?.[k] ?? 0));
for (let t = 10; t <= 15; t++) { const tr = mean(X, (D) => ext(D, 'enhTry_t' + t)), ok = mean(X, (D) => ext(D, 'enhOk_t' + t)), dr = mean(X, (D) => ext(D, 'enhDrop_t' + t)), fl = mean(X, (D) => ext(D, 'enhFail_t' + t)); w(`| +${t} | ${RT[t]} | ${f1(tr)} | ${f1(ok)} | ${tr ? P(ok / tr) : '—'} | ${f1(dr)} | ${t >= 13 ? f1(fl - dr) : '—'} |`); }
const tries = mean(X, (D) => sum([10, 11, 12, 13, 14, 15].map((t) => ext(D, 'enhTry_t' + t)))), oks = mean(X, (D) => sum([10, 11, 12, 13, 14, 15].map((t) => ext(D, 'enhOk_t' + t)))), eg = mean(X, (D) => ext(D, 'enhGold'));
w(`\n- Deneme başına ortalama akçe **${f0(eg / Math.max(1, tries))}**, başarılı yükseltme başına **${f0(eg / Math.max(1, oks))}** · başarısız deneme akçesi ${Mn(eg * (1 - oks / Math.max(1, tries)))} · demir cevheri ${f0(mean(X, (D) => ext(D, 'enhOre')))} · Tılsım ${f1(mean(X, (D) => ext(D, 'enhCharm')))} · kitap ${f1(mean(X, (D) => ext(D, 'enhBook')))}.`);
{ const stock = (R: any[], k: 'charm' | 'book') => avg(R.map((D) => avg(D.agents.filter(mature).map((a: any) => a.final.bag[k])))); w(`- Koruma eşyası: olgun kohortta gün sonu stok/oyuncu — Tılsım ${f1(stock(C, 'charm'))} (K) → ${f1(stock(X, 'charm'))}, kitap ${f1(stock(C, 'book'))} (K) → ${f1(stock(X, 'book'))}; sunucunun reddettiği deneme (ör. günlük sınır) ${f0(mean(X, (D) => ext(D, 'enhRejected')))}.`); }
w(`- Engel kayıtları: bütçe ${f0(mean(X, (D) => ext(D, 'enhBlockBudget')))} · akçe ${f0(mean(X, (D) => ext(D, 'enhBlockGold')))} · cevher ${f0(mean(X, (D) => ext(D, 'enhBlockOre')))} · riskten vazgeçme ${f0(mean(X, (D) => ext(D, 'enhSkippedRisk')))}.\n`);
w('## 2. Gerçek sink oluşuyor mu?\n\n| Metrik | Kontrol | ' + LABEL + ' | Fark |\n|---|---|---|---|');
row('Toplam kaynak', mean(EC, (e) => e.src), mean(EX, (e) => e.src), Mn); row('Toplam sink', mean(EC, (e) => e.snk), mean(EX, (e) => e.snk), Mn); row('Sink/kaynak', mean(EC, (e) => e.snk / e.src), mean(EX, (e) => e.snk / e.src), P); row('Net akçe artışı', mean(EC, (e) => e.net), mean(EX, (e) => e.net), Mn); row(`G${DAYS} toplam akçe`, mean(EC, (e) => e.tot), mean(EX, (e) => e.tot), Mn); row('Medyan bakiye', mean(EC, (e) => e.med), mean(EX, (e) => e.med), K); row('Üst %10 bakiye', mean(EC, (e) => e.top), mean(EX, (e) => e.top), K);
w(`\n- **+10…+15 sink / toplam kaynak: ${P(mean(EX, (e) => e.g.enh / e.src))}** · **+10…+15 sink / toplam sink: ${P(mean(EX, (e) => e.g.enh / e.snk))}** (toplam ${Mn(mean(EX, (e) => e.g.enh))}).\n`);
w('**İkame (kalem grupları, Kontrol → ' + LABEL + '):**\n\n| Kalem | Kontrol | ' + LABEL + ' | Fark |\n|---|---|---|---|');
for (const [k, n] of [['enh', '+10…+15 (yeni)'], ['kostum', 'Kostüm (tezgâh/üretim/efsun/uzatma/görünüm)'], ['luck', 'Şans eşyası'], ['kimiz', 'Kımız'], ['up9', 'Artı basma (+1…+9)'], ['other', 'Diğer (beceri, efsun yenileme, üretim, pazar, zindan…)']]) row(n, mean(EC, (e) => e.g[k]), mean(EX, (e) => e.g[k]), Mn);
const dSink = mean(EX, (e) => e.snk) - mean(EC, (e) => e.snk), dEnh = mean(EX, (e) => e.g.enh); w(`\n- Net sink farkı ${Mn(dSink)} / doğrudan +10…+15 sink ${Mn(dEnh)} → ikame/yer değiştirme ≈ **${Mn(dEnh - dSink)}** (pozitif: diğer harcamalar azaldı).\n`);
w('## 3. Güç yoğunlaşması (oyuncu gücü = saldırı × azami can)\n');
const conc = (D: any, d: number, pick: (a: any) => boolean) => { const du = D.dayUps[d - 1]; const pw = D.agents.map((a: any, i: number) => (pick(a) ? du.agents[i].power : -1)).filter((x: number) => x >= 0).sort((a: number, b: number) => a - b); const n = pw.length; const med = pw[Math.floor(n / 2)]; const top10 = avg(pw.slice(Math.floor(n * 0.9))); const top1 = avg(pw.slice(Math.max(0, Math.ceil(n * 0.99) - 1))); return { t1: top1 / med, t10: top10 / med, t1_10: top1 / top10 }; };
for (const [name, pick] of [['Tüm nüfus', () => true], ['Olgun +9 kohortu', mature]] as [string, (a: any) => boolean][]) {
  w(`**${name}**\n\n| Gün | Üst %1 / medyan (K → v1.1) | Üst %10 / medyan (K → v1.1) |\n|---|---|---|`);
  for (const d of snaps.filter((x) => x >= 7)) { w(`| ${d} | ${f2(mean(C, (D) => conc(D, d, pick).t1))} → ${f2(mean(X, (D) => conc(D, d, pick).t1))} | ${f2(mean(C, (D) => conc(D, d, pick).t10))} → ${f2(mean(X, (D) => conc(D, d, pick).t10))} |`); }
  w();
}
w('_Üst %1, 150 oyuncuda 1–2 oyuncu (kohortta 1) olduğundan gürültülüdür; üst %10 daha güvenilirdir._\n');
w('## 4. Combat (son gün ekipmanından / tüm koşudan)\n\n| Metrik | Kontrol | ' + LABEL + ' | Fark |\n|---|---|---|---|');
const cm = (D: any) => { const ag: any[] = D.agents; const pw = ag.map((a) => { const s = stats(a); return s.atk * s.maxHp; }); const ord = pw.map((x, i) => i).sort((a, b) => pw[a] - pw[b]); const n = ord.length; const mid = ord.slice(Math.floor(n * 0.4), Math.ceil(n * 0.6)).map((i) => ag[i]); const top = ord.slice(Math.floor(n * 0.9)).map((i) => ag[i]); const pairs = (A: any[], B: any[]) => avg(A.flatMap((a) => B.filter((b) => b !== a).map((b) => ttk(a, b)))); const bf: any[] = D.bossFights, dl: any[] = D.dunLog; const hrs = sum(ag.map((a) => sum(a.days.map((d: any) => d.minutes)))) / 60; return { mm: pairs(mid, mid), tm: pairs(top, mid), mt: pairs(mid, top), boss: avg(bf.map((b) => b.sec)), win: dl.length ? dl.filter((x) => x.state === 'won').length / dl.length : 0, dph: sum(ag.map((a) => a.tot.deaths + a.tot.extraDeaths)) / Math.max(1, hrs) }; };
const MC = C.map(cm), MX = X.map(cm);
row('PvP TTK orta bant→orta bant (sn)', mean(MC, (m) => m.mm), mean(MX, (m) => m.mm), f1); row('PvP TTK üst %10→orta bant (sn)', mean(MC, (m) => m.tm), mean(MX, (m) => m.tm), f1); row('PvP TTK orta bant→üst %10 (sn)', mean(MC, (m) => m.mt), mean(MX, (m) => m.mt), f1); row('Boss TTK (sn)', mean(MC, (m) => m.boss), mean(MX, (m) => m.boss), f1); row('Zindan kazanma', mean(MC, (m) => m.win), mean(MX, (m) => m.win), P); row('Ölüm/saat (tüm nüfus)', mean(MC, (m) => m.dph), mean(MX, (m) => m.dph), f2);
w('\n## 5. Profil kırılımı (deney kolu, olgun kohort, gün sonu)\n\n| Grup | Oyuncu | Deneme/oyuncu | Düşme/oyuncu | Ort. en yüksek +n | Harcanan akçe/oyuncu |\n|---|---|---|---|---|---|');
const ag = X.flatMap((D) => D.agents).filter(mature); const grp = (name: string, key: string, lo: number, hi: number) => { const g = ag.filter((a: any) => a.par[key] >= lo && a.par[key] < hi); if (!g.length) return; const e = (a: any, k: string) => a.ext?.[k] ?? 0; const T = [10, 11, 12, 13, 14, 15]; w(`| ${name} | ${g.length} | ${f1(sum(g.map((a: any) => sum(T.map((t) => e(a, 'enhTry_t' + t))))) / g.length)} | ${f1(sum(g.map((a: any) => sum(T.map((t) => e(a, 'enhDrop_t' + t))))) / g.length)} | ${f1(avg(g.map((a: any) => Math.max(0, ...Object.values(a.def as Record<string, Item>).map((i) => i.up)))))} | ${f0(sum(g.map((a: any) => e(a, 'enhGold'))) / g.length)} |`); };
grp('risk iştahı düşük (<0,33)', 'riskAppetite', 0, 0.33); grp('risk iştahı orta', 'riskAppetite', 0.33, 0.67); grp('risk iştahı yüksek (≥0,67)', 'riskAppetite', 0.67, 2); grp('bütçe oranı düşük (<0,13)', 'upBudget', 0, 0.13); grp('bütçe oranı orta', 'upBudget', 0.13, 0.22); grp('bütçe oranı yüksek (≥0,22)', 'upBudget', 0.22, 2);
writeFileSync(process.argv[4] ?? '/tmp/enh11_long.md', L.join('\n')); console.log(L.join('\n'));
